export const INDUSTRY_CATEGORIES = {
    retail: [
        "Apparel & Clothing",
        "Footwear & Shoes",
        "Jewelry & Accessories",
        "Handbags & Luggage",
        "Watches & Timepieces",
        "Sunglasses & Eyewear",
        "Cosmetics & Beauty",
        "Skincare Products",
        "Hair Care Products",
        "Perfumes & Fragrances",
        "Home Decor & Furnishings",
        "Furniture & Seating",
        "Lighting & Lamps",
        "Bedding & Linens",
        "Curtains & Window Treatments",
        "Rugs & Carpets",
        "Wall Art & Pictures",
        "Candles & Air Fresheners",
        "Kitchenware & Cookware",
        "Small Kitchen Appliances",
        "Dinnerware & Tableware",
        "Glassware & Drinkware",
        "Storage & Organization",
        "Cleaning Supplies",
        "Electronics & Gadgets",
        "Mobile Phones & Accessories",
        "Headphones & Audio",
        "Computer Accessories",
        "Gaming Accessories",
        "Toys & Games",
        "Books & Magazines",
        "Stationery & Office Supplies",
        "Art & Craft Supplies",
        "Sports & Recreation",
        "Fitness Equipment",
        "Outdoor & Camping",
        "Garden & Plants",
        "Pet Supplies",
        "Baby & Kids Products",
        "Health & Wellness",
        "Food & Beverages",
        "Snacks & Confectionery",
        "Gift Cards & Vouchers",
        "Seasonal Items",
        "Holiday Decorations",
        "Travel Accessories",
        "Automotive Accessories",
        "Tools & Hardware",
        "Personal Care Items",
        "Musical Instruments"
    ],

    manufacturing: [
        "Raw Materials",
        "Steel & Metal Alloys",
        "Aluminum Products",
        "Copper & Brass",
        "Plastics & Polymers",
        "Rubber & Elastomers",
        "Glass & Ceramics",
        "Wood & Timber",
        "Textiles & Fabrics",
        "Chemical Compounds",
        "Industrial Adhesives",
        "Lubricants & Oils",
        "Paints & Coatings",
        "Electronic Components",
        "Semiconductors",
        "Circuit Boards",
        "Sensors & Actuators",
        "Motors & Drives",
        "Bearings & Seals",
        "Fasteners & Hardware",
        "Welding Materials",
        "Cutting Tools",
        "Machine Parts",
        "Hydraulic Components",
        "Pneumatic Components",
        "Safety Equipment",
        "Protective Gear",
        "Industrial Filters",
        "Conveyor Systems",
        "Packaging Materials",
        "Labels & Marking",
        "Quality Control Instruments",
        "Measuring Tools",
        "Testing Equipment",
        "Maintenance Supplies",
        "Workshop Tools",
        "Assembly Line Components",
        "Automation Equipment",
        "Robotics Components",
        "Control Systems",
        "Power Transmission",
        "Electrical Components",
        "Cables & Wiring",
        "Insulation Materials",
        "Heat Treatment Materials",
        "Surface Treatment",
        "Finishing Materials",
        "Precision Components",
        "Tooling & Dies",
        "Jigs & Fixtures"
    ],
    wholesale: [
        "Paper Towels",
        "Toilet Paper",
        "Cleaning Supplies",
        "Detergents",
        "Bleach",
        "Dish Soap",
        "Shampoo",
        "Conditioner",
        "Body Wash",
        "Toothpaste",
        "Deodorant",
        "Soap Bars",
        "Hand Sanitizer",
        "Tissues",
        "Napkins",
        "Plastic Bags",
        "Aluminum Foil",
        "Canned Soup",
        "Pasta",
        "Rice",
        "Cereal",
        "Snack Bars",
        "Crackers",
        "Chips",
        "Soft Drinks",
        "Water Bottles",
        "Energy Drinks",
        "Coffee",
        "Tea",
        "Juice",
        "Office Paper",
        "Pens",
        "Pencils",
        "Notebooks",
        "Folders",
        "Staplers",
        "Paper Clips",
        "Rubber Bands",
        "Tape",
        "Scissors",
        "Calculators",
        "Desk Chairs",
        "Filing Cabinets",
        "Printers",
        "Ink Cartridges",
        "Computer Mice",
        "Keyboards",
        "USB Drives",
        "Power Cables",
        "Extension Cords",
        "Light Bulbs",
        "Batteries",
        "Gift Cards",
        "Seasonal Decorations"
    ],
    logistics: [
        "Shipping Containers",
        "Cardboard Boxes",
        "Bubble Wrap",
        "Packing Peanuts",
        "Stretch Film",
        "Shrink Wrap",
        "Packing Tape",
        "Shipping Labels",
        "Fragile Stickers",
        "Warning Labels",
        "Barcodes",
        "QR Code Labels",
        "Wooden Pallets",
        "Plastic Pallets",
        "Metal Pallets",
        "Pallet Wraps",
        "Corner Protectors",
        "Edge Guards",
        "Foam Padding",
        "Air Pillows",
        "Truck Tires",
        "Brake Pads",
        "Engine Oil",
        "Transmission Fluid",
        "Coolant",
        "Air Filters",
        "Fuel Filters",
        "Spark Plugs",
        "Windshield Wipers",
        "Headlights",
        "Tail Lights",
        "Turn Signals",
        "Mirrors",
        "GPS Units",
        "Radio Systems",
        "CB Radios",
        "Tracking Devices",
        "Dashcams",
        "Cargo Straps",
        "Tie-Down Chains",
        "Bungee Cords",
        "Tarps",
        "Load Bars",
        "Dock Plates",
        "Loading Ramps",
        "Lift Gates",
        "Pallet Jacks",
        "Hand Trucks",
        "Dollies",
        "Warehouse Carts",
        "Conveyor Rollers",
        "Loading Docks",
        "Safety Cones",
        "Reflective Vests"
    ],
    healthcare: [
        "Syringes",
        "Needles",
        "Surgical Gloves",
        "Face Masks",
        "Surgical Gowns",
        "Hair Nets",
        "Shoe Covers",
        "Disposable Caps",
        "Bandages",
        "Gauze Pads",
        "Medical Tape",
        "Adhesive Bandages",
        "Antiseptic Wipes",
        "Alcohol Swabs",
        "Iodine Solution",
        "Hydrogen Peroxide",
        "Saline Solution",
        "IV Bags",
        "IV Tubing",
        "Catheters",
        "Stethoscopes",
        "Blood Pressure Cuffs",
        "Thermometers",
        "Pulse Oximeters",
        "ECG Electrodes",
        "Defibrillator Pads",
        "Surgical Scissors",
        "Forceps",
        "Scalpels",
        "Sutures",
        "Surgical Staples",
        "Clamps",
        "Retractors",
        "Speculums",
        "Otoscopes",
        "Ophthalmoscopes",
        "Reflex Hammers",
        "Tongue Depressors",
        "Cotton Swabs",
        "Specimen Containers",
        "Test Tubes",
        "Petri Dishes",
        "Microscope Slides",
        "Cover Slips",
        "Pipettes",
        "Centrifuge Tubes",
        "Laboratory Glassware",
        "Chemical Reagents",
        "Culture Media",
        "pH Strips",
        "Pregnancy Tests",
        "Blood Glucose Strips",
        "Urinalysis Strips",
        "Hearing Aids"
    ],
    "food-beverage": [
        "Apples",
        "Bananas",
        "Oranges",
        "Lettuce",
        "Tomatoes",
        "Carrots",
        "Potatoes",
        "Onions",
        "Bell Peppers",
        "Broccoli",
        "Spinach",
        "Cucumbers",
        "Fresh Herbs",
        "Organic Vegetables",
        "Milk",
        "Cheese",
        "Yogurt",
        "Butter",
        "Eggs",
        "Cream",
        "Ice Cream",
        "Chicken Breast",
        "Ground Beef",
        "Pork Chops",
        "Fresh Fish",
        "Shrimp",
        "Salmon",
        "Lunch Meat",
        "Hot Dogs",
        "Bacon",
        "Bread",
        "Bagels",
        "Croissants",
        "Muffins",
        "Cakes",
        "Cookies",
        "Pastries",
        "Pizza Dough",
        "Canned Tomatoes",
        "Chicken Broth",
        "Soup",
        "Pasta Sauce",
        "Olive Oil",
        "Vinegar",
        "Spices",
        "Salt",
        "Sugar",
        "Flour",
        "Frozen Meals",
        "Frozen Vegetables",
        "Frozen Fruit",
        "Ice",
        "Soda",
        "Mineral Water"
    ],
    automotive: [
        "Engine Blocks",
        "Pistons",
        "Cylinder Heads",
        "Valve Covers",
        "Timing Belts",
        "Timing Chains",
        "Spark Plugs",
        "Ignition Coils",
        "Fuel Injectors",
        "Fuel Pumps",
        "Air Filters",
        "Oil Filters",
        "Fuel Filters",
        "Radiators",
        "Water Pumps",
        "Thermostats",
        "Cooling Fans",
        "Hoses",
        "Belts",
        "Alternators",
        "Starters",
        "Batteries",
        "Headlights",
        "Tail Lights",
        "Turn Signals",
        "Fog Lights",
        "LED Bulbs",
        "Halogen Bulbs",
        "Car Stereos",
        "Speakers",
        "Amplifiers",
        "GPS Navigation",
        "Backup Cameras",
        "Dash Cams",
        "Car Alarms",
        "Remote Starters",
        "Window Tinting",
        "Car Covers",
        "Floor Mats",
        "Seat Covers",
        "Steering Wheel Covers",
        "Air Fresheners",
        "Phone Mounts",
        "USB Chargers",
        "Jump Starters",
        "Tire Pressure Gauges",
        "Car Wash Soap",
        "Wax",
        "Polish",
        "Detailing Brushes",
        "Microfiber Cloths",
        "Chamois",
        "Tire Shine",
        "Glass Cleaner"
    ],
    electronics: [
        "CPUs",
        "GPUs",
        "Motherboards",
        "RAM Memory",
        "SSD Drives",
        "Hard Drives",
        "Power Supplies",
        "CPU Coolers",
        "Case Fans",
        "Computer Cases",
        "Keyboards",
        "Computer Mice",
        "Monitors",
        "Webcams",
        "Microphones",
        "Headphones",
        "Speakers",
        "USB Cables",
        "HDMI Cables",
        "Ethernet Cables",
        "Power Cords",
        "Extension Cables",
        "Resistors",
        "Capacitors",
        "Inductors",
        "Diodes",
        "Transistors",
        "Integrated Circuits",
        "Microcontrollers",
        "Arduino Boards",
        "Raspberry Pi",
        "Breadboards",
        "Jumper Wires",
        "Soldering Iron",
        "Solder Wire",
        "Flux",
        "Multimeters",
        "Oscilloscopes",
        "Function Generators",
        "Power Analyzers",
        "Spectrum Analyzers",
        "Logic Analyzers",
        "Bench Power Supplies",
        "Signal Generators",
        "Network Analyzers",
        "LCR Meters",
        "Insulation Testers",
        "Clamp Meters",
        "Thermal Cameras",
        "Digital Calipers",
        "Wire Strippers",
        "Crimping Tools",
        "Heat Shrink Tubing",
        "Electrical Tape"
    ],
    fashion: [
        "Polo Shirts",
        "Button-Down Shirts",
        "Henley Shirts",
        "Tank Tops",
        "Muscle Shirts",
        "Long-Sleeve Shirts",
        "Graphic Tees",
        "V-Neck Shirts",
        "Crew Neck Shirts",
        "Turtlenecks",
        "Cargo Pants",
        "Chinos",
        "Dress Pants",
        "Sweatpants",
        "Joggers",
        "Leggings",
        "Capri Pants",
        "Shorts",
        "Board Shorts",
        "Compression Shorts",
        "Mini Skirts",
        "Maxi Skirts",
        "Pencil Skirts",
        "A-Line Skirts",
        "Pleated Skirts",
        "Wrap Skirts",
        "Shift Dresses",
        "Maxi Dresses",
        "Midi Dresses",
        "Bodycon Dresses",
        "Wrap Dresses",
        "Shirt Dresses",
        "Sweater Dresses",
        "Blazers",
        "Cardigans",
        "Pullovers",
        "Zip-Up Hoodies",
        "Pullover Hoodies",
        "Fleece Jackets",
        "Denim Jackets",
        "Leather Jackets",
        "Bomber Jackets",
        "Trench Coats",
        "Peacoats",
        "Parkas",
        "Vests",
        "Crop Tops",
        "Tube Tops",
        "Camisoles",
        "Sports Jerseys",
        "Team Apparel",
        "Concert Tees",
        "Vintage Band Shirts",
        "Streetwear"
    ],
    construction: [
        "Concrete Mix",
        "Cement Bags",
        "Sand",
        "Gravel",
        "Crushed Stone",
        "Rebar",
        "Steel Beams",
        "Lumber",
        "Plywood",
        "OSB Boards",
        "Drywall",
        "Insulation",
        "Roofing Shingles",
        "Metal Roofing",
        "Gutters",
        "Downspouts",
        "Flashing",
        "Roofing Nails",
        "Screws",
        "Bolts",
        "Washers",
        "Nuts",
        "Anchors",
        "Brackets",
        "Hinges",
        "Door Handles",
        "Locks",
        "Windows",
        "Doors",
        "Trim",
        "Molding",
        "Baseboards",
        "Crown Molding",
        "Flooring",
        "Carpet",
        "Tile",
        "Hardwood",
        "Laminate",
        "Vinyl",
        "Paint",
        "Primer",
        "Brushes",
        "Rollers",
        "Drop Cloths",
        "Ladder",
        "Scaffolding",
        "Hand Tools",
        "Power Tools",
        "Safety Equipment",
        "Hard Hats",
        "Safety Glasses",
        "Work Gloves",
        "Tool Belts",
        "Measuring Tape"
    ],
    pharmaceutical: [
        "Aspirin",
        "Ibuprofen",
        "Acetaminophen",
        "Antibiotics",
        "Blood Pressure Medication",
        "Cholesterol Medication",
        "Diabetes Medication",
        "Heart Medication",
        "Antidepressants",
        "Anxiety Medication",
        "Pain Relievers",
        "Anti-inflammatory",
        "Antihistamines",
        "Decongestants",
        "Cough Syrup",
        "Cold Medicine",
        "Fever Reducers",
        "Allergy Pills",
        "Sleep Aids",
        "Vitamins",
        "Minerals",
        "Supplements",
        "Probiotics",
        "Protein Powder",
        "Fish Oil",
        "Calcium",
        "Iron",
        "Vitamin D",
        "Vitamin C",
        "B-Complex",
        "Multivitamins",
        "Herbal Supplements",
        "Weight Loss Pills",
        "Energy Drinks",
        "Meal Replacements",
        "Blood Glucose Meters",
        "Test Strips",
        "Insulin",
        "Syringes",
        "Needles",
        "Bandages",
        "First Aid Kits",
        "Thermometers",
        "Blood Pressure Monitors",
        "Pulse Oximeters",
        "Inhalers",
        "Nebulizers",
        "CPAP Machines",
        "Wheelchairs",
        "Walkers",
        "Crutches",
        "Hearing Aids",
        "Reading Glasses",
        "Contact Lenses"
    ]
} as const;

export type Industry = keyof typeof INDUSTRY_CATEGORIES;

export const getIndustryCategories = (industry: string): string[] => {
    const normalizedIndustry = industry.toLowerCase().replace(/\s+/g, '-') as Industry;
    return [...(INDUSTRY_CATEGORIES[normalizedIndustry] || [])];
};

export const getAllIndustries = (): Industry[] => {
    return Object.keys(INDUSTRY_CATEGORIES) as Industry[];
};
